apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wil-playground
  namespace: argocd
spec:
  project: iot-project
  source:
    repoURL: https://github.com/phm-aguiar/Inception-of-Things-phenriq2
    targetRevision: HEAD
    path: p3/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
