apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: iot-project
  namespace: argocd
spec:
  description: Inception of Things project
  sourceRepos:
  - https://github.com/phm-aguiar/Inception-of-Things-phenriq2
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
